# Generated by Django 4.1.2 on 2022-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0002_appliance_task_homearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sid',
            field=models.CharField(default=22, max_length=128),
            preserve_default=False,
        ),
    ]
