# Generated by Django 4.1.2 on 2022-10-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='handy_dandy_api.user')),
                ('hvac', models.BooleanField(default=False)),
                ('electrical', models.BooleanField(default=False)),
                ('carpentry', models.BooleanField(default=False)),
                ('plumbing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handy_dandy_api.user'),
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
