# Generated by Django 4.1.2 on 2022-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0006_competencies_user_is_pro_alter_task_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencies',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='appliance',
        ),
        migrations.RemoveField(
            model_name='task',
            name='diy_links',
        ),
        migrations.AddField(
            model_name='competencies',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
