# Generated by Django 4.1.2 on 2022-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0008_alter_competencies_carpentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='carpentry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='hvac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='plumbing',
            field=models.BooleanField(default=False),
        ),
    ]
