# Generated by Django 4.1.2 on 2022-10-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0009_alter_competencies_carpentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handy_dandy_api.competencies'),
        ),
    ]
