# Generated by Django 4.1.2 on 2022-10-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0010_user_competencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='competencies',
        ),
    ]
