# Generated by Django 4.1.2 on 2022-10-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0011_remove_user_competencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencies',
            name='owner',
            field=models.ForeignKey(default=777, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='handy_dandy_api.user'),
            preserve_default=False,
        ),
    ]
