# Generated by Django 4.1.2 on 2022-10-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0013_alter_competencies_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handy_dandy_api.user'),
        ),
    ]
