# Generated by Django 4.1.2 on 2022-10-27 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0016_alter_competencies_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='handy_dandy_api.user'),
        ),
    ]
