# Generated by Django 4.1.2 on 2022-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_dandy_api', '0017_alter_competencies_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='home_area',
            new_name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='period_months',
            field=models.CharField(max_length=12),
        ),
    ]
